name: Convert PDF to Markdown

on:
  push:
    paths:
    - '**.md'

jobs:
  convert_md: 
    runs-on: ubuntu-latest
    steps:
    # We must checkout the latest version of the code to get a copy of all .md files
    - name: Checkout Code
      uses: actions/checkout@v2.0.0
      with:
        fetch-depth: 1
    - name: Create .pdfs
      uses: scottypate/md-to-pdf@v0.1.1
      env: {
        # Use this parameter to determine where the generated .pdf(s) will be stored.
        PDF_DIR: './pdfs'
      }
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v1.6.1
      uses: Perdoo/pull-request-update-body-action@v1.0.1
      with:
        ghToken: ${{ secrets.GITHUB_TOKEN }}
        body: "Hello World!"

